CREATE SCHEMA IF NOT EXISTS url;

CREATE TABLE url.urls (
    id SERIAL PRIMARY KEY,
    short_url VARCHAR(64) NOT NULL,
    original_url TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
